# Where things are
source:       .
destination:  ./_site
# plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


# Site config
title: yongle
# description:
# keywords:
# url:
feed: /atom.xml
favicon: /images/shortcut.png

# Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html

# Author config
author:
    name: lyuyongle
    email: lyuyongle@gmail.com
    imageLink: /images/header.jpeg
    simpleIntro: 米乐乐果<br>2019 全局、逻辑、目标。<br>2018 耐心
    detailIntro:
      <p>筚路蓝缕，以启山林。</p>

# Pick icon at http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/
  - class: icon-facebook
    url: https://www.facebook.com/yongle.lyu.9
  - class: icon-github-alt
    url: https://github.com/lyltj2010
  - class: icon-twitter
    url: https://twitter.com/lvyongle
  - class: icon-google-plus
    url: https://plus.google.com/u/0/100808276953752695030

#Links
customLinks:
  - item:
    - text: 阳志平
      url: http://www.yangzhiping.com/
    - text: 肖凯老师
      url: http://xccds1977.blogspot.jp/
    message: Friends

# googleAnaly
googleAnaly:
  config: false
  id:

# baidu tongji
baiduTongji:
  config: true
  id: e8bf647c2591fb56e719969be3d529c9

# comment config
disqus:
  config:
  id:

duoshuo:
  config: false
  id:

# baidu share config
baiduShare:
  config: false
  
